const countries = [
  {
    name: "USA",
    value: "US",
    cites: ["New York", "Los Angeles", "Chicago"],
  },
  {
    name: "Canada",
    value: "CA",
    cites: ["Toronto", "Vancouver", "Montreal"],
  },
  {
    name: "United Kingdom",
    value: "GB",
    cites: ["London", "Manchester", "Birmingham"],
  },
  {
    name: "Australia",
    value: "AU",
    cites: ["Sydney", "Melbourne", "Brisbane"],
  },
  {
    name: "India",
    value: "IN",
    cites: ["Mumbai", "Delhi", "Bangalore"],
  },
  {
    name: "Germany",
    value: "DE",
    cities: [
      "City 1 of Germany",
      "City 2 of Germany",
      "City 3 of Germany",
      "City 4 of Germany",
      "City 5 of Germany",
      "City 6 of Germany",
      "City 7 of Germany",
      "City 8 of Germany",
      "City 9 of Germany",
      "City 10 of Germany",
    ],
  },
  {
    name: "France",
    value: "FR",
    cities: [
      "City 1 of France",
      "City 2 of France",
      "City 3 of France",
      "City 4 of France",
      "City 5 of France",
      "City 6 of France",
      "City 7 of France",
      "City 8 of France",
      "City 9 of France",
      "City 10 of France",
    ],
  },
  {
    name: "Italy",
    value: "IT",
    cities: [
      "City 1 of Italy",
      "City 2 of Italy",
      "City 3 of Italy",
      "City 4 of Italy",
      "City 5 of Italy",
      "City 6 of Italy",
      "City 7 of Italy",
      "City 8 of Italy",
      "City 9 of Italy",
      "City 10 of Italy",
    ],
  },
  {
    name: "Spain",
    value: "ES",
    cities: [
      "City 1 of Spain",
      "City 2 of Spain",
      "City 3 of Spain",
      "City 4 of Spain",
      "City 5 of Spain",
      "City 6 of Spain",
      "City 7 of Spain",
      "City 8 of Spain",
      "City 9 of Spain",
      "City 10 of Spain",
    ],
  },
  {
    name: "Brazil",
    value: "BR",
    cities: [
      "City 1 of Brazil",
      "City 2 of Brazil",
      "City 3 of Brazil",
      "City 4 of Brazil",
      "City 5 of Brazil",
      "City 6 of Brazil",
      "City 7 of Brazil",
      "City 8 of Brazil",
      "City 9 of Brazil",
      "City 10 of Brazil",
    ],
  },
  {
    name: "Mexico",
    value: "MX",
    cities: [
      "City 1 of Mexico",
      "City 2 of Mexico",
      "City 3 of Mexico",
      "City 4 of Mexico",
      "City 5 of Mexico",
      "City 6 of Mexico",
      "City 7 of Mexico",
      "City 8 of Mexico",
      "City 9 of Mexico",
      "City 10 of Mexico",
    ],
  },
  {
    name: "Russia",
    value: "RU",
    cities: [
      "City 1 of Russia",
      "City 2 of Russia",
      "City 3 of Russia",
      "City 4 of Russia",
      "City 5 of Russia",
      "City 6 of Russia",
      "City 7 of Russia",
      "City 8 of Russia",
      "City 9 of Russia",
      "City 10 of Russia",
    ],
  },
  {
    name: "China",
    value: "CN",
    cities: [
      "City 1 of China",
      "City 2 of China",
      "City 3 of China",
      "City 4 of China",
      "City 5 of China",
      "City 6 of China",
      "City 7 of China",
      "City 8 of China",
      "City 9 of China",
      "City 10 of China",
    ],
  },
  {
    name: "Japan",
    value: "JP",
    cities: [
      "City 1 of Japan",
      "City 2 of Japan",
      "City 3 of Japan",
      "City 4 of Japan",
      "City 5 of Japan",
      "City 6 of Japan",
      "City 7 of Japan",
      "City 8 of Japan",
      "City 9 of Japan",
      "City 10 of Japan",
    ],
  },
  {
    name: "South Korea",
    value: "KR",
    cities: [
      "City 1 of South Korea",
      "City 2 of South Korea",
      "City 3 of South Korea",
      "City 4 of South Korea",
      "City 5 of South Korea",
      "City 6 of South Korea",
      "City 7 of South Korea",
      "City 8 of South Korea",
      "City 9 of South Korea",
      "City 10 of South Korea",
    ],
  },
  {
    name: "Indonesia",
    value: "ID",
    cities: [
      "City 1 of Indonesia",
      "City 2 of Indonesia",
      "City 3 of Indonesia",
      "City 4 of Indonesia",
      "City 5 of Indonesia",
      "City 6 of Indonesia",
      "City 7 of Indonesia",
      "City 8 of Indonesia",
      "City 9 of Indonesia",
      "City 10 of Indonesia",
    ],
  },
  {
    name: "South Africa",
    value: "ZA",
    cities: [
      "City 1 of South Africa",
      "City 2 of South Africa",
      "City 3 of South Africa",
      "City 4 of South Africa",
      "City 5 of South Africa",
      "City 6 of South Africa",
      "City 7 of South Africa",
      "City 8 of South Africa",
      "City 9 of South Africa",
      "City 10 of South Africa",
    ],
  },
  {
    name: "Nigeria",
    value: "NG",
    cities: [
      "City 1 of Nigeria",
      "City 2 of Nigeria",
      "City 3 of Nigeria",
      "City 4 of Nigeria",
      "City 5 of Nigeria",
      "City 6 of Nigeria",
      "City 7 of Nigeria",
      "City 8 of Nigeria",
      "City 9 of Nigeria",
      "City 10 of Nigeria",
    ],
  },
  {
    name: "Egypt",
    value: "EG",
    cities: [
      "City 1 of Egypt",
      "City 2 of Egypt",
      "City 3 of Egypt",
      "City 4 of Egypt",
      "City 5 of Egypt",
      "City 6 of Egypt",
      "City 7 of Egypt",
      "City 8 of Egypt",
      "City 9 of Egypt",
      "City 10 of Egypt",
    ],
  },
  {
    name: "Turkey",
    value: "TR",
    cities: [
      "City 1 of Turkey",
      "City 2 of Turkey",
      "City 3 of Turkey",
      "City 4 of Turkey",
      "City 5 of Turkey",
      "City 6 of Turkey",
      "City 7 of Turkey",
      "City 8 of Turkey",
      "City 9 of Turkey",
      "City 10 of Turkey",
    ],
  },
];
export default countries;
